---
title: "Bivariate Viz"
author: Robert Reiss
date: 9-13-24
---
```{r}
library(tidyverse)
```

```{r}
# Load data
elections <- read.csv("https://mac-stat.github.io/data/election_2020_county.csv")

# Check it out
head(elections)
```
# Exercise 0 a
43%

```{r}
ggplot(elections, aes(x = winner_20)) + geom_bar()
```
# Exercise 0b

```{r}
ggplot(elections, aes(x = repub_pct_20))+geom_histogram(color = "white")
```

# Exercise 2

```{r}
ggplot(elections, aes(x = repub_pct_16, y = repub_pct_20))+geom_point()

# Change the shape of the points
# What happens if you change the shape to another number?
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) +
  geom_point(shape = 3)

# YOU TRY: Modify the code to make the points "orange"
# NOTE: Try to anticipate if "color" or "fill" will be useful here. Then try both.
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) +
  geom_point(color="orange")

# Add a layer that represents each county by the state it's in
# Take note of the geom and the info it needs to run!
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) +
  geom_text(aes(label = state_abbr))
```

# Exercise 4
```{r}
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) +
  geom_point() +
  geom_smooth()

ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) + geom_smooth()

ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) + geom_smooth(method = "lm")
```

# Exercise 5

```{r}
# Scatterplot of repub_pct_20 vs median_rent
ggplot(elections, aes(y = repub_pct_20, x = median_rent)) + geom_point()


# Scatterplot of repub_pct_20 vs median_age
ggplot(elections, aes(y = repub_pct_20, x = median_age)) + geom_point()
```

# Exercise 7

```{r}
# Side-by-side violin plots
ggplot(elections, aes(y = repub_pct_20, x = historical)) +
  geom_violin()

# Side-by-side boxplots (defined below)
ggplot(elections, aes(y = repub_pct_20, x = historical)) +
  geom_boxplot()
```

# Exercise 8

```{r}
ggplot(elections, aes(x = repub_pct_20, fill = historical)) +
  geom_density()
```

# Exercise 9
```{r}
# What does scale_fill_manual do?
ggplot(elections, aes(x = repub_pct_20, fill = historical)) +
  geom_density() +
  scale_fill_manual(values = c("blue", "purple", "red"))

# What does alpha = 0.5 do?
# Play around with different values of alpha, between 0 and 1
ggplot(elections, aes(x = repub_pct_20, fill = historical)) +
  geom_density(alpha = 0.5) +
  scale_fill_manual(values = c("blue", "purple", "red"))

# What does facet_wrap do?!
ggplot(elections, aes(x = repub_pct_20, fill = historical)) +
  geom_density() +
  scale_fill_manual(values = c("blue", "purple", "red")) +
  facet_wrap(~ historical)
```

