project:
  type: book
  output-dir: docs

book:
  title: "COMP/STAT112 Notebook"
  author: "Your Name Here"
  date: "Date Here"
  reader-mode: true
  
  chapters:
    - index.qmd

    - part: activities/README.qmd
      chapters: 
      - activities/activity-01.qmd
      - activities/activity-02.qmd
      - activities/activity-03.qmd
      - activities/activity_04.qmd
      - activities/activity_05.qmd
      - activities/activity_06.qmd
      - activities/activity_07.qmd
      - activities/activity_08.qmd
      - activities/activity_09.qmd
  
    - part: journal
      chapters: 
        - journal/9_4_24.qmd
        - journal/9_6_24.qmd
        - journal/9_10_24 entry.qmd
        - journal/9_11_24.qmd
        - journal/9_12_24.qmd
        - journal/9_16_24.qmd
        - journal/9_19_24.qmd
        - journal/9_22_24.qmd
        - journal/9_27_24.qmd
        - journal/10_1_24.qmd
        - journal/10_3_24.qmd
    
    - part: notes/README.qmd
      chapters: 
      - notes/note-01.qmd
      - notes/note-02.qmd
      


format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-line-numbers: true
    code-tools: true

execute:
  cache: false
  freeze: auto
